CREATE OR ALTER TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
  ,AGE VARCHAR
  ,SALARY NUMBER
);
INSERT INTO HELLO_WORLD VALUES ('ABHISHEK','SHARMA','34',25000);
INSERT INTO HELLO_WORLD VALUES ('ABHISHEK','SEN','34',25000);
INSERT INTO HELLO_WORLD VALUES ('CHINMAY','SHARMA','34',20000);
