name: snowflake-devops-demo

on:
  push:
    branches:
      - dev_cicd_1
      - main

jobs:
  schemachange:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install schemachange

    - name: Deploy to DEV_changes
      env: 
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      if: github.ref == 'refs/heads/dev_cicd_1'
      run: python schemachange_runner2.py dev

    - name: Deploy to Prod
      env: 
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      if: github.ref == 'refs/heads/main'
      run: python schemachange_runner2.py prod
