name: snowflake-devops-demo

on:
  push:
    branches:
      - dev
      - main

jobs:
  schemachange:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install schemachange

    - name: Deploy to Dev
      if: github.ref == 'refs/heads/DEV_changes'
      run: python schemachange_runner.py dev

    - name: Deploy to Prod
      if: github.ref == 'refs/heads/main'
      run: python schemachange_runner.py prod
